### ISSUE TITLE
Use variables to manage gradle android dependencies library version numbers

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#271]
**Use variables to manage gradle android dependencies library version numbers**

- At the moment some of the version numbers are hardcoded as 1.0.2 etc

**Would you like to work on the issue?**
Yes

**Comment by victorvicari** [comment]
Good one @gconnect . Perhaps, since it's a kotlin project, make use of BuildSrc...
https://handstandsam.com/2018/02/11/kotlin-buildsrc-for-better-gradle-dependency-management/
the link above will give you a nice idea about BuildSrc, what are the pros and how it actually work.
Not mandatory, although, nice to know.

**Comment by gconnect** [comment]
Thanks @victorvicari will check it out!

**Comment by gconnect** [comment]
I have sent PR for this. Thanks once again @victorvicari  for your suggestion.
