### ISSUE TITLE
Design CampaignList Detail Page Mockup 

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#338]
**Create Campaign Details Page**
- At the moment there is no detail page for the campaign list item

**Steps to reproduce**
- Create mockup design for campaign details page with Figma
- Implement the design on the android studio(XML)

**Would you like to work on the issue?**
Yes

**Comment by gconnect** [comment]
![image](https://user-images.githubusercontent.com/23031920/73665892-31100080-46a2-11ea-93a8-326a9c84d958.png)

Here is the link to the design https://www.figma.com/file/6gYtosgx6qt1RKRw922rfP/wikidashboard?node-id=107%3A161

**Comment by ujjwalagrawal17** [comment]
The design looks great to me. Feedback from my end

- I suggest we can use BottomSheetDialogs instead of expandable items in recyclerview in courses, editors, articles tabs.  
- Create Campaign Page should not be in the details page of campaign. Also, I think in our app we don't need this feature as of now. 
- Edit, Delete buttons can be there in the actions section. I am not sure how many people will use the download-stats feature. We can remove this if possible. 
- The values can be highlighted in (bold+accentColor) instead of the titles in all 3 tabs(programs, editors, articles).
Ex.- "Words Added" is a title and doesn't need attention. The value "5.6k" should be highlighted instead.

For WikiEdu Dashboard Some text changes will be there: 
Programs -> Courses. 
Editors -> Students.

**Comment by ujjwalagrawal17** [comment]
Also toolbar title can be in black color.

**Comment by gconnect** [comment]
Noted.Thanks for checking

**Comment by gconnect** [comment]
![image](https://user-images.githubusercontent.com/23031920/73758840-6cc2cd00-476b-11ea-8c9f-2f316529c9c6.png)

![image](https://user-images.githubusercontent.com/23031920/73758866-751b0800-476b-11ea-96a1-8b171bb434f2.png)

![image](https://user-images.githubusercontent.com/23031920/73758895-79472580-476b-11ea-9206-b46eb5e955dd.png)


![image](https://user-images.githubusercontent.com/23031920/73758816-66345580-476b-11ea-892d-055b5c131205.png)

**Comment by gconnect** [comment]
Please review @ujjwalagrawal17

**Comment by ujjwalagrawal17** [comment]
Looks good to me. 

Instead of downarrow icon we can use 3 dot-menu icon.
The titles in the bottom sheet[articleName, studentName, courseName] are not very clear, we can add a divider between title and remaining section. Also, the font size of title can be increased.

**Comment by gconnect** [comment]
Do you mean three dots vertically or horizontally?

**Comment by gconnect** [comment]
![image](https://user-images.githubusercontent.com/23031920/73829385-23be5780-4803-11ea-8e9a-a580ed0f2f8f.png)
![image](https://user-images.githubusercontent.com/23031920/73829388-24ef8480-4803-11ea-9c3b-c2bdc9c5d212.png)
![image](https://user-images.githubusercontent.com/23031920/73829416-2f118300-4803-11ea-99b0-27a20276ed98.png)
![image](https://user-images.githubusercontent.com/23031920/73829407-2a4ccf00-4803-11ea-9e04-de8792b40bdc.png)

**Comment by gconnect** [comment]
Please review @ujjwalagrawal17

**Comment by ujjwalagrawal17** [comment]
Looks perfect. We can start the implementation. 😁

**Comment by ujjwalagrawal17** [comment]
Thanks @gconnect . Closing this issue.
