### ISSUE TITLE
Add Firebase Crash Analytics to get crash reports

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#54]
**Describe the feature you'd like**

Add Firebase Crash Analytics to get crash reports

**Link:** https://firebase.google.com/docs/crashlytics

**Comment by MarinaTaran** [comment]
Can I take this one?

**Comment by ujjwalagrawal17** [comment]
Umm, we are not planning to assign it to a new comer now. You can maybe start with #65 .

**Comment by MarinaTaran** [comment]
Could you think about to give me this task? I done it onсe in my project. Maybe I can try to solve it?

**Comment by ujjwalagrawal17** [comment]
Actually I am not sure if we should implement firebase crashlytics or any other open source crash reporting tool. If you want you can help us in comparing pros and cons of using other tools instead of firebase.

**Comment by MarinaTaran** [comment]
ok, I will check

**Comment by MarinaTaran** [comment]
**Backlog**
Made for developers, Backlog is an online project management solution that includes bug tracking. The system allows you to see where all of your bugs fit into your overall project workflow. You can document work with as many details as you want or need, and create custom fields to resolve issues efficiently.
         ### Pros:
 backlog users love that the free version of the system includes access to a wiki and said that the system, overall, is easy to use and set up.
        ### Cons :
some users noted that the reporting and data analysis features could be improved to allow more in-depth insights.
Users who want something easy to use no matter their business size.

       **Bugzilla**
Bugzilla is an open source tool that offers powerful search capabilities, duplicate bug detection, time tracking, and a patch reviewer that makes it easier to read lines of code. You can leave private comments and notes within a bug, and grant access to specific bugs to relevant/necessary team members.
        ###  Pros :
Bugzilla users love that the software is easy to use with a low learning curve.
         ### Cons :
Users note that if your needs are more complex, the system’s “basic” setup can make it feel sparse. And most reviewers think the interface could use a facelift.
Users who work in quality assurance or businesses that want something without any distracting bells and whistles.

       **MantisBT**
Built on PHP (hypertext preprocessor) and is compatible with MySQL and PostgreSQL databases. It’s commonly used as a bug tracker, but you can configure the system to manage larger software development projects as well. MantisBT offers access control that you can change per project, customizable issue fields, notifications, and workflows, as well as a mobile-optimized UI add-on if your team needs mobile access.
       ###   Pros:
Reviewers found that MantisBT is easy enough for an experienced programmer to use, but noted that an average user might require some training.
         ### Cros :  
Users said that although MantisBT’s interface is outdated, it still offers all the basic features a software development team needs to track and fix bugs.
 Senior software engineers or developers who want something customizable.

          **Redmine**
Redmine is more than just a bug tracker. This open source project management solution has been around for over a decade and supports 34 different languages. Redmine is written in Ruby, and is compatible with MySQL, PostgreSQL, Microsoft SQL, and SQLite.
          ### Pros:
Users of Redmine generally find a basic version of the system easy to implement and fairly easy to use.
         Cros : 
If you’re just looking for bug tracking, Redmine might be a little more than you bargained for, but you can use the flexibility of its customizable interface and the slew of available plugins to adapt the system to your team’s needs over time.
 Project managers in the IT service field.

          **Zoho** **BugTracker**
Zoho is an online suite of software solutions that includes a free bug tracker. Zoho BugTracker works for companies of all sizes, and allows project collaboration to help users resolve issues faster. The free version allows up to five users on one project.
      ###Pros :
 Users find the tool easy to use and report that it has great functionality.
      ###  Cros:
Reviewers say that the company’s customer service could be improved.
C-suite users and business founders who want insight into their issue tracking, and developers looking for an easy-to-use tool.

             **Tuleap.**
 Its issue tracking system is really powerful: each project team can create new trackers, add new fields, change layout, permissions by field etc. , triggers CI jobs, changes on child trackers, be linked to Git, SVN, Eclipse and so on. Try it here : demo.tuleap.org

            **Backlog**
https://backlogtool.com/ which is an issue and bug tracking software made for developers. It has the added functionality of Git/SVN and Wiki in one. It’s free for teams of 10.
 #1: Confusion and miscommunication among team members.
Solution: Get everyone on the same page with better communication. Companies can manage all their projects in one single place that is accessible to everyone within the organization. Everyone can have access to the most updated information on the status of a project. Using Backlog also drastically reduces the number of emails and instances of missed emails.
 #2: Meeting project and task deadlines.
Solution: Users improve their workflow and stay on track with the project’s deadlines. Clear due dates and progress tracking assist with better managing tasks.
 #3: Central storage of critical information.
Solution: All information pertaining to projects can be stored in the wiki or the relevant tickets. These can include images, videos, and links. For example, documents are often updated and the team will always have easy access to the most updated version and previous versions.

          **Bugrem**
Feedback of someone : I'd like to recomend BugRem tool at https://bugrem.com. I have been using this tool for quite sometime now. It allows me to submit criticism/feedback and bug reports by means of screen capture. As a client, I could also hide any delicate data on the image. Since it is lightweight (less than 8KB), it didn't slowed down my site. In addition to that, it is simple to incorporate to my site. Based from its features, the tool works with a variety of tools like Jira, Trello, etc.

Maybe you can give me  more information what do you looking for? Why you are  not sure if you should implement firebase crashlytics  or any other?

**Comment by ujjwalagrawal17** [comment]
Closing this as this is a less priority feature as of now.
